title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

# There is a symlink of the siteroot/thync pointing to siteroot so local file structure matches what is pushed to GitHub
# GitHub serves the files with the prefix of the project name so this makes the local site behave like the published one
# This exclusion tells Jekyll to stop after one recursive call
exclude: [thync/thync]
